# Generated by Django 3.1.3 on 2020-11-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='dosen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='hari',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='jam',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
